pull_request_rules:
  - name: Request reviews automatically
    conditions:
      - -draft
      - "#review-requested = 0"
    actions:
      request_reviews:
        teams:
          - "@acme/maintainers"
        users:
          - OmarBader-dev
